### PR TITLE
Upgrade dune to 3.0 and rip out reason

### PR DESCRIPTION
**Pull request by bleepbloopsify**
no reason 

(i literally just ripped out anything to do with reason, and updated react. This is tested in this PR:https://github.com/skolemlabs/code/pull/629)

it works great

### CODE REVIEW

**Comment by bleepbloopsify** [comment]
I also removed the example app that was written entirely in reason, (maybe they will add another one in pure ocaml upstream)

**Review by zbaylin — CHANGES_REQUESTED** [review]
DNM, fixed in ml-in-barcelona/jsoo-react#162

**Comment by bleepbloopsify** [comment]
@zbaylin I merged upstream and did a conflict resolution, (we still want dune 3.0 because it supports JS things)

**Comment by bleepbloopsify** [comment]
closing because they fixed everything in upstream

**Pull request closed without merging**
